services:
  - type: web
    name: connectlocal-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 4000
      - key: TWILIO_ACCOUNT_SID
        value: your_twilio_sid
      - key: TWILIO_AUTH_TOKEN
        value: your_twilio_auth_token
      - key: TWILIO_PHONE_NUMBER
        value: your_twilio_number
